# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.7
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: sebas6612@gmail.com
author_name: sebas6612
cloud_provider: none
preset_name: production
project_name: gacha_web_public-frontend

