# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.11
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: sebas6612@gmail.com
author_name: sebas6612
cloud_provider: none
contract_name: gacha_contract
deployment_language: python
preset_name: production
project_name: gacha_web_public

